name: Copy
on: push
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: "."
        dst_path: "/.github/workflows/"
        dst_owner: markcheret
        dst_repo_name: cheret-org
        dst_branch: main
        src_branch: main
        file_filter: "*.yml"
        exclude: "/.github/workflows/*.yml"
        username: markcheret
        email: mark@cheret.de
        commit_message: "workflows: update to latest version"